spring:
  application:
    name: "cp-seller-api"
  profiles:
    include:
      - domain-rds

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8091
  tomcat:
    uri-encoding: utf-8